using System.ComponentModel.DataAnnotations;
using tickethub.Models;

namespace tickethub.Tests.Orders;

public class OrderTests
{
    private static List<ValidationResult> ValidateModel(object model)
    {
        var validationResults = new List<ValidationResult>();
        var validationContext = new ValidationContext(model);
        Validator.TryValidateObject(model, validationContext, validationResults, true);
        return validationResults;
    }

    private static Concert CreateValidConcert(int id = 1)
    {
        return new Concert
        {
            Id = id,
            Title = "Metallica",
            Start = DateTime.UtcNow.AddDays(10),
            MaxCapacity = 5000,
            TicketPrice = 675,
            TicketsSold = 0
        };
    }

    private static Order CreateValidOrder(
        string customerEmail = "customer@example.com",
        int qty = 1,
        decimal unitPrice = 675,
        Concert? concert = null)
    {
        concert ??= CreateValidConcert();

        return new Order
        {
            CustomerEmail = customerEmail,
            Qty = qty,
            UnitPrice = unitPrice,
            ConcertId = concert.Id,
            Concert = concert
        };
    }

    [Fact]
    public void ValidOrder_ShouldPassValidation()
    {
        var order = CreateValidOrder();
        var results = ValidateModel(order);
        Assert.Empty(results);
    }

    [Fact]
    public void Id_ShouldBeGuidType()
    {
        var order = CreateValidOrder();
        Assert.IsType<Guid>(order.Id);
    }

    [Fact]
    public void Id_ShouldBeAutoGeneratedAndUnique()
    {
        var order1 = CreateValidOrder();
        var order2 = CreateValidOrder();

        Assert.NotEqual(Guid.Empty, order1.Id);
        Assert.NotEqual(Guid.Empty, order2.Id);
        Assert.NotEqual(order1.Id, order2.Id);
    }

    [Fact]
    public void EmptyEmail_ShouldFailValidation()
    {
        var order = CreateValidOrder(customerEmail: string.Empty);
        var results = ValidateModel(order);
        Assert.NotEmpty(results);
    }

    [Fact]
    public void EmailMissingAtSymbol_ShouldFailValidation()
    {
        var order = CreateValidOrder(customerEmail: "customerexample.com");
        var results = ValidateModel(order);
        Assert.Single(results);
    }

    [Fact]
    public void EmailWithEmptyLocalPart_ShouldFailValidation()
    {
        var order = CreateValidOrder(customerEmail: "@example.com");
        var results = ValidateModel(order);
        Assert.Single(results);
    }

    [Fact]
    public void EmailWithEmptyDomainPart_ShouldFailValidation()
    {
        var order = CreateValidOrder(customerEmail: "customer@");
        var results = ValidateModel(order);
        Assert.Single(results);
    }

    [Fact]
    public void EmailWith254Characters_ShouldPassValidation()
    {
        const string domainPart = "@a.com";
        var localPart = new string('a', 254 - domainPart.Length); 
        var email = $"{localPart}{domainPart}";
        
        var order = CreateValidOrder(customerEmail: email);
        var results = ValidateModel(order);
        
        Assert.Empty(results);
    }

    [Fact]
    public void EmailWith255Characters_ShouldFailValidation()
    {
        const string domainPart = "@a.com";
        var localPart = new string('a', 255 - domainPart.Length); 
        var email = $"{localPart}{domainPart}";
        
        var order = CreateValidOrder(customerEmail: email);
        var results = ValidateModel(order);
        
        Assert.Single(results);
    }

    [Fact]
    public void ZeroQty_ShouldFailValidation()
    {
        var order = CreateValidOrder(qty: 0);
        var results = ValidateModel(order);
        Assert.Single(results);
    }

    [Fact]
    public void NegativeQty_ShouldFailValidation()
    {
        var order = CreateValidOrder(qty: -1);
        var results = ValidateModel(order);
        Assert.Single(results);
    }

    [Fact]
    public void PositiveQty_ShouldPassValidation()
    {
        var order = CreateValidOrder(qty: 1);
        var results = ValidateModel(order);
        Assert.Empty(results);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    public void ValidUnitPrice_ShouldPassValidation(decimal price)
    {
        var order = CreateValidOrder(unitPrice: price);
        var results = ValidateModel(order);
        Assert.Empty(results);
    }

    [Fact]
    public void NegativeUnitPrice_ShouldFailValidation()
    {
        var order = CreateValidOrder(unitPrice: -1);
        var results = ValidateModel(order);
        Assert.Single(results);
    }

    [Fact]
    public void Order_ShouldLinkToProvidedConcert()
    {
        var concert = CreateValidConcert(id: 42);
        var order = CreateValidOrder(concert: concert);

        Assert.Equal(concert.Id, order.ConcertId);
        Assert.Same(concert, order.Concert);
    }
}