@tickethub_HostAddress = http://localhost:5234

POST {{tickethub_HostAddress}}/api/concerts
Content-Type: application/json
Accept: application/json

{
  "title": "Metallica",
  "start": "2026-08-15T20:00:00Z",
  "maxCapacity": 5000,
  "ticketPrice": 675.00
}